global using Microsoft.EntityFrameworkCore;
global using ErrorOr;
global using Ordering.Domain.Entities;
global using Ordering.Application.Data;
global using Ordering.Application.Dtos;
global using BuildingBlocks.CQRS;
global using FluentValidation;
global using Ordering.Domain.ValueObjects;
global using Ordering.Domain.Errors;
